// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: starmessage.proto

#include "starmessage.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_starmessage_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_nodeinfo_starmessage_2eproto;
namespace txstar {
class nodeinfoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<nodeinfo> _instance;
} _nodeinfo_default_instance_;
class successorReqDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<successorReq> _instance;
} _successorReq_default_instance_;
class successorRspDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<successorRsp> _instance;
} _successorRsp_default_instance_;
class successorNtfDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<successorNtf> _instance;
} _successorNtf_default_instance_;
class joinReqDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<joinReq> _instance;
} _joinReq_default_instance_;
class joinRspDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<joinRsp> _instance;
} _joinRsp_default_instance_;
class stabilizeReqDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<stabilizeReq> _instance;
} _stabilizeReq_default_instance_;
class stabilizeRspDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<stabilizeRsp> _instance;
} _stabilizeRsp_default_instance_;
}  // namespace txstar
static void InitDefaultsscc_info_joinReq_starmessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::txstar::_joinReq_default_instance_;
    new (ptr) ::txstar::joinReq();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::txstar::joinReq::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_joinReq_starmessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_joinReq_starmessage_2eproto}, {
      &scc_info_nodeinfo_starmessage_2eproto.base,}};

static void InitDefaultsscc_info_joinRsp_starmessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::txstar::_joinRsp_default_instance_;
    new (ptr) ::txstar::joinRsp();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::txstar::joinRsp::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_joinRsp_starmessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_joinRsp_starmessage_2eproto}, {
      &scc_info_nodeinfo_starmessage_2eproto.base,}};

static void InitDefaultsscc_info_nodeinfo_starmessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::txstar::_nodeinfo_default_instance_;
    new (ptr) ::txstar::nodeinfo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::txstar::nodeinfo::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_nodeinfo_starmessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_nodeinfo_starmessage_2eproto}, {}};

static void InitDefaultsscc_info_stabilizeReq_starmessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::txstar::_stabilizeReq_default_instance_;
    new (ptr) ::txstar::stabilizeReq();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::txstar::stabilizeReq::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_stabilizeReq_starmessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_stabilizeReq_starmessage_2eproto}, {
      &scc_info_nodeinfo_starmessage_2eproto.base,}};

static void InitDefaultsscc_info_stabilizeRsp_starmessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::txstar::_stabilizeRsp_default_instance_;
    new (ptr) ::txstar::stabilizeRsp();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::txstar::stabilizeRsp::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_stabilizeRsp_starmessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_stabilizeRsp_starmessage_2eproto}, {
      &scc_info_nodeinfo_starmessage_2eproto.base,}};

static void InitDefaultsscc_info_successorNtf_starmessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::txstar::_successorNtf_default_instance_;
    new (ptr) ::txstar::successorNtf();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::txstar::successorNtf::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_successorNtf_starmessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_successorNtf_starmessage_2eproto}, {
      &scc_info_nodeinfo_starmessage_2eproto.base,}};

static void InitDefaultsscc_info_successorReq_starmessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::txstar::_successorReq_default_instance_;
    new (ptr) ::txstar::successorReq();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::txstar::successorReq::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_successorReq_starmessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_successorReq_starmessage_2eproto}, {
      &scc_info_nodeinfo_starmessage_2eproto.base,}};

static void InitDefaultsscc_info_successorRsp_starmessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::txstar::_successorRsp_default_instance_;
    new (ptr) ::txstar::successorRsp();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::txstar::successorRsp::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_successorRsp_starmessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_successorRsp_starmessage_2eproto}, {
      &scc_info_nodeinfo_starmessage_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_starmessage_2eproto[8];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_starmessage_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_starmessage_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_starmessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::txstar::nodeinfo, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::txstar::nodeinfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::txstar::nodeinfo, nodeid_),
  PROTOBUF_FIELD_OFFSET(::txstar::nodeinfo, address_),
  PROTOBUF_FIELD_OFFSET(::txstar::nodeinfo, port_),
  2,
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::txstar::successorReq, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::txstar::successorReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::txstar::successorReq, node_),
  0,
  PROTOBUF_FIELD_OFFSET(::txstar::successorRsp, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::txstar::successorRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::txstar::successorRsp, node_),
  0,
  PROTOBUF_FIELD_OFFSET(::txstar::successorNtf, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::txstar::successorNtf, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::txstar::successorNtf, node_),
  0,
  PROTOBUF_FIELD_OFFSET(::txstar::joinReq, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::txstar::joinReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::txstar::joinReq, node_),
  0,
  PROTOBUF_FIELD_OFFSET(::txstar::joinRsp, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::txstar::joinRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::txstar::joinRsp, nxt_),
  PROTOBUF_FIELD_OFFSET(::txstar::joinRsp, pre_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::txstar::stabilizeReq, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::txstar::stabilizeReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::txstar::stabilizeReq, node_),
  0,
  PROTOBUF_FIELD_OFFSET(::txstar::stabilizeRsp, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::txstar::stabilizeRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::txstar::stabilizeRsp, pre_),
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::txstar::nodeinfo)},
  { 11, 17, sizeof(::txstar::successorReq)},
  { 18, 24, sizeof(::txstar::successorRsp)},
  { 25, 31, sizeof(::txstar::successorNtf)},
  { 32, 38, sizeof(::txstar::joinReq)},
  { 39, 46, sizeof(::txstar::joinRsp)},
  { 48, 54, sizeof(::txstar::stabilizeReq)},
  { 55, 61, sizeof(::txstar::stabilizeRsp)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::txstar::_nodeinfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::txstar::_successorReq_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::txstar::_successorRsp_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::txstar::_successorNtf_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::txstar::_joinReq_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::txstar::_joinRsp_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::txstar::_stabilizeReq_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::txstar::_stabilizeRsp_default_instance_),
};

const char descriptor_table_protodef_starmessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021starmessage.proto\022\006txstar\"9\n\010nodeinfo\022"
  "\016\n\006nodeid\030\001 \002(\r\022\017\n\007address\030\002 \002(\t\022\014\n\004port"
  "\030\003 \002(\t\".\n\014successorReq\022\036\n\004node\030\001 \002(\0132\020.t"
  "xstar.nodeinfo\".\n\014successorRsp\022\036\n\004node\030\001"
  " \002(\0132\020.txstar.nodeinfo\".\n\014successorNtf\022\036"
  "\n\004node\030\001 \002(\0132\020.txstar.nodeinfo\")\n\007joinRe"
  "q\022\036\n\004node\030\001 \002(\0132\020.txstar.nodeinfo\"G\n\007joi"
  "nRsp\022\035\n\003nxt\030\001 \002(\0132\020.txstar.nodeinfo\022\035\n\003p"
  "re\030\002 \002(\0132\020.txstar.nodeinfo\".\n\014stabilizeR"
  "eq\022\036\n\004node\030\001 \002(\0132\020.txstar.nodeinfo\"-\n\014st"
  "abilizeRsp\022\035\n\003pre\030\001 \002(\0132\020.txstar.nodeinf"
  "o"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_starmessage_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_starmessage_2eproto_sccs[8] = {
  &scc_info_joinReq_starmessage_2eproto.base,
  &scc_info_joinRsp_starmessage_2eproto.base,
  &scc_info_nodeinfo_starmessage_2eproto.base,
  &scc_info_stabilizeReq_starmessage_2eproto.base,
  &scc_info_stabilizeRsp_starmessage_2eproto.base,
  &scc_info_successorNtf_starmessage_2eproto.base,
  &scc_info_successorReq_starmessage_2eproto.base,
  &scc_info_successorRsp_starmessage_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_starmessage_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_starmessage_2eproto = {
  false, false, descriptor_table_protodef_starmessage_2eproto, "starmessage.proto", 441,
  &descriptor_table_starmessage_2eproto_once, descriptor_table_starmessage_2eproto_sccs, descriptor_table_starmessage_2eproto_deps, 8, 0,
  schemas, file_default_instances, TableStruct_starmessage_2eproto::offsets,
  file_level_metadata_starmessage_2eproto, 8, file_level_enum_descriptors_starmessage_2eproto, file_level_service_descriptors_starmessage_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_starmessage_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_starmessage_2eproto)), true);
namespace txstar {

// ===================================================================

void nodeinfo::InitAsDefaultInstance() {
}
class nodeinfo::_Internal {
 public:
  using HasBits = decltype(std::declval<nodeinfo>()._has_bits_);
  static void set_has_nodeid(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_address(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_port(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000007) ^ 0x00000007) != 0;
  }
};

nodeinfo::nodeinfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:txstar.nodeinfo)
}
nodeinfo::nodeinfo(const nodeinfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_address()) {
    address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_address(),
      GetArena());
  }
  port_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_port()) {
    port_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_port(),
      GetArena());
  }
  nodeid_ = from.nodeid_;
  // @@protoc_insertion_point(copy_constructor:txstar.nodeinfo)
}

void nodeinfo::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_nodeinfo_starmessage_2eproto.base);
  address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  port_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  nodeid_ = 0u;
}

nodeinfo::~nodeinfo() {
  // @@protoc_insertion_point(destructor:txstar.nodeinfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void nodeinfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  address_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  port_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void nodeinfo::ArenaDtor(void* object) {
  nodeinfo* _this = reinterpret_cast< nodeinfo* >(object);
  (void)_this;
}
void nodeinfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void nodeinfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const nodeinfo& nodeinfo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_nodeinfo_starmessage_2eproto.base);
  return *internal_default_instance();
}


void nodeinfo::Clear() {
// @@protoc_insertion_point(message_clear_start:txstar.nodeinfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      address_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      port_.ClearNonDefaultToEmpty();
    }
  }
  nodeid_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* nodeinfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required uint32 nodeid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_nodeid(&has_bits);
          nodeid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required string address = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_address();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "txstar.nodeinfo.address");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required string port = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_port();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "txstar.nodeinfo.port");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* nodeinfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:txstar.nodeinfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 nodeid = 1;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_nodeid(), target);
  }

  // required string address = 2;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_address().data(), static_cast<int>(this->_internal_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "txstar.nodeinfo.address");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_address(), target);
  }

  // required string port = 3;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_port().data(), static_cast<int>(this->_internal_port().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "txstar.nodeinfo.port");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_port(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:txstar.nodeinfo)
  return target;
}

size_t nodeinfo::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:txstar.nodeinfo)
  size_t total_size = 0;

  if (_internal_has_address()) {
    // required string address = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_address());
  }

  if (_internal_has_port()) {
    // required string port = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_port());
  }

  if (_internal_has_nodeid()) {
    // required uint32 nodeid = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_nodeid());
  }

  return total_size;
}
size_t nodeinfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:txstar.nodeinfo)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string address = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_address());

    // required string port = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_port());

    // required uint32 nodeid = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_nodeid());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void nodeinfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:txstar.nodeinfo)
  GOOGLE_DCHECK_NE(&from, this);
  const nodeinfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<nodeinfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:txstar.nodeinfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:txstar.nodeinfo)
    MergeFrom(*source);
  }
}

void nodeinfo::MergeFrom(const nodeinfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:txstar.nodeinfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_address(from._internal_address());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_port(from._internal_port());
    }
    if (cached_has_bits & 0x00000004u) {
      nodeid_ = from.nodeid_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void nodeinfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:txstar.nodeinfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void nodeinfo::CopyFrom(const nodeinfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:txstar.nodeinfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool nodeinfo::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void nodeinfo::InternalSwap(nodeinfo* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  address_.Swap(&other->address_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  port_.Swap(&other->port_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(nodeid_, other->nodeid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata nodeinfo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void successorReq::InitAsDefaultInstance() {
  ::txstar::_successorReq_default_instance_._instance.get_mutable()->node_ = const_cast< ::txstar::nodeinfo*>(
      ::txstar::nodeinfo::internal_default_instance());
}
class successorReq::_Internal {
 public:
  using HasBits = decltype(std::declval<successorReq>()._has_bits_);
  static const ::txstar::nodeinfo& node(const successorReq* msg);
  static void set_has_node(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::txstar::nodeinfo&
successorReq::_Internal::node(const successorReq* msg) {
  return *msg->node_;
}
successorReq::successorReq(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:txstar.successorReq)
}
successorReq::successorReq(const successorReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_node()) {
    node_ = new ::txstar::nodeinfo(*from.node_);
  } else {
    node_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:txstar.successorReq)
}

void successorReq::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_successorReq_starmessage_2eproto.base);
  node_ = nullptr;
}

successorReq::~successorReq() {
  // @@protoc_insertion_point(destructor:txstar.successorReq)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void successorReq::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete node_;
}

void successorReq::ArenaDtor(void* object) {
  successorReq* _this = reinterpret_cast< successorReq* >(object);
  (void)_this;
}
void successorReq::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void successorReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const successorReq& successorReq::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_successorReq_starmessage_2eproto.base);
  return *internal_default_instance();
}


void successorReq::Clear() {
// @@protoc_insertion_point(message_clear_start:txstar.successorReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(node_ != nullptr);
    node_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* successorReq::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .txstar.nodeinfo node = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_node(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* successorReq::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:txstar.successorReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .txstar.nodeinfo node = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::node(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:txstar.successorReq)
  return target;
}

size_t successorReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:txstar.successorReq)
  size_t total_size = 0;

  // required .txstar.nodeinfo node = 1;
  if (_internal_has_node()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *node_);
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void successorReq::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:txstar.successorReq)
  GOOGLE_DCHECK_NE(&from, this);
  const successorReq* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<successorReq>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:txstar.successorReq)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:txstar.successorReq)
    MergeFrom(*source);
  }
}

void successorReq::MergeFrom(const successorReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:txstar.successorReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_node()) {
    _internal_mutable_node()->::txstar::nodeinfo::MergeFrom(from._internal_node());
  }
}

void successorReq::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:txstar.successorReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void successorReq::CopyFrom(const successorReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:txstar.successorReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool successorReq::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (_internal_has_node()) {
    if (!node_->IsInitialized()) return false;
  }
  return true;
}

void successorReq::InternalSwap(successorReq* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(node_, other->node_);
}

::PROTOBUF_NAMESPACE_ID::Metadata successorReq::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void successorRsp::InitAsDefaultInstance() {
  ::txstar::_successorRsp_default_instance_._instance.get_mutable()->node_ = const_cast< ::txstar::nodeinfo*>(
      ::txstar::nodeinfo::internal_default_instance());
}
class successorRsp::_Internal {
 public:
  using HasBits = decltype(std::declval<successorRsp>()._has_bits_);
  static const ::txstar::nodeinfo& node(const successorRsp* msg);
  static void set_has_node(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::txstar::nodeinfo&
successorRsp::_Internal::node(const successorRsp* msg) {
  return *msg->node_;
}
successorRsp::successorRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:txstar.successorRsp)
}
successorRsp::successorRsp(const successorRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_node()) {
    node_ = new ::txstar::nodeinfo(*from.node_);
  } else {
    node_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:txstar.successorRsp)
}

void successorRsp::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_successorRsp_starmessage_2eproto.base);
  node_ = nullptr;
}

successorRsp::~successorRsp() {
  // @@protoc_insertion_point(destructor:txstar.successorRsp)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void successorRsp::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete node_;
}

void successorRsp::ArenaDtor(void* object) {
  successorRsp* _this = reinterpret_cast< successorRsp* >(object);
  (void)_this;
}
void successorRsp::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void successorRsp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const successorRsp& successorRsp::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_successorRsp_starmessage_2eproto.base);
  return *internal_default_instance();
}


void successorRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:txstar.successorRsp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(node_ != nullptr);
    node_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* successorRsp::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .txstar.nodeinfo node = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_node(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* successorRsp::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:txstar.successorRsp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .txstar.nodeinfo node = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::node(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:txstar.successorRsp)
  return target;
}

size_t successorRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:txstar.successorRsp)
  size_t total_size = 0;

  // required .txstar.nodeinfo node = 1;
  if (_internal_has_node()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *node_);
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void successorRsp::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:txstar.successorRsp)
  GOOGLE_DCHECK_NE(&from, this);
  const successorRsp* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<successorRsp>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:txstar.successorRsp)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:txstar.successorRsp)
    MergeFrom(*source);
  }
}

void successorRsp::MergeFrom(const successorRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:txstar.successorRsp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_node()) {
    _internal_mutable_node()->::txstar::nodeinfo::MergeFrom(from._internal_node());
  }
}

void successorRsp::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:txstar.successorRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void successorRsp::CopyFrom(const successorRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:txstar.successorRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool successorRsp::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (_internal_has_node()) {
    if (!node_->IsInitialized()) return false;
  }
  return true;
}

void successorRsp::InternalSwap(successorRsp* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(node_, other->node_);
}

::PROTOBUF_NAMESPACE_ID::Metadata successorRsp::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void successorNtf::InitAsDefaultInstance() {
  ::txstar::_successorNtf_default_instance_._instance.get_mutable()->node_ = const_cast< ::txstar::nodeinfo*>(
      ::txstar::nodeinfo::internal_default_instance());
}
class successorNtf::_Internal {
 public:
  using HasBits = decltype(std::declval<successorNtf>()._has_bits_);
  static const ::txstar::nodeinfo& node(const successorNtf* msg);
  static void set_has_node(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::txstar::nodeinfo&
successorNtf::_Internal::node(const successorNtf* msg) {
  return *msg->node_;
}
successorNtf::successorNtf(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:txstar.successorNtf)
}
successorNtf::successorNtf(const successorNtf& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_node()) {
    node_ = new ::txstar::nodeinfo(*from.node_);
  } else {
    node_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:txstar.successorNtf)
}

void successorNtf::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_successorNtf_starmessage_2eproto.base);
  node_ = nullptr;
}

successorNtf::~successorNtf() {
  // @@protoc_insertion_point(destructor:txstar.successorNtf)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void successorNtf::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete node_;
}

void successorNtf::ArenaDtor(void* object) {
  successorNtf* _this = reinterpret_cast< successorNtf* >(object);
  (void)_this;
}
void successorNtf::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void successorNtf::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const successorNtf& successorNtf::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_successorNtf_starmessage_2eproto.base);
  return *internal_default_instance();
}


void successorNtf::Clear() {
// @@protoc_insertion_point(message_clear_start:txstar.successorNtf)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(node_ != nullptr);
    node_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* successorNtf::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .txstar.nodeinfo node = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_node(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* successorNtf::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:txstar.successorNtf)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .txstar.nodeinfo node = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::node(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:txstar.successorNtf)
  return target;
}

size_t successorNtf::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:txstar.successorNtf)
  size_t total_size = 0;

  // required .txstar.nodeinfo node = 1;
  if (_internal_has_node()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *node_);
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void successorNtf::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:txstar.successorNtf)
  GOOGLE_DCHECK_NE(&from, this);
  const successorNtf* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<successorNtf>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:txstar.successorNtf)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:txstar.successorNtf)
    MergeFrom(*source);
  }
}

void successorNtf::MergeFrom(const successorNtf& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:txstar.successorNtf)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_node()) {
    _internal_mutable_node()->::txstar::nodeinfo::MergeFrom(from._internal_node());
  }
}

void successorNtf::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:txstar.successorNtf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void successorNtf::CopyFrom(const successorNtf& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:txstar.successorNtf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool successorNtf::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (_internal_has_node()) {
    if (!node_->IsInitialized()) return false;
  }
  return true;
}

void successorNtf::InternalSwap(successorNtf* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(node_, other->node_);
}

::PROTOBUF_NAMESPACE_ID::Metadata successorNtf::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void joinReq::InitAsDefaultInstance() {
  ::txstar::_joinReq_default_instance_._instance.get_mutable()->node_ = const_cast< ::txstar::nodeinfo*>(
      ::txstar::nodeinfo::internal_default_instance());
}
class joinReq::_Internal {
 public:
  using HasBits = decltype(std::declval<joinReq>()._has_bits_);
  static const ::txstar::nodeinfo& node(const joinReq* msg);
  static void set_has_node(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::txstar::nodeinfo&
joinReq::_Internal::node(const joinReq* msg) {
  return *msg->node_;
}
joinReq::joinReq(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:txstar.joinReq)
}
joinReq::joinReq(const joinReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_node()) {
    node_ = new ::txstar::nodeinfo(*from.node_);
  } else {
    node_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:txstar.joinReq)
}

void joinReq::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_joinReq_starmessage_2eproto.base);
  node_ = nullptr;
}

joinReq::~joinReq() {
  // @@protoc_insertion_point(destructor:txstar.joinReq)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void joinReq::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete node_;
}

void joinReq::ArenaDtor(void* object) {
  joinReq* _this = reinterpret_cast< joinReq* >(object);
  (void)_this;
}
void joinReq::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void joinReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const joinReq& joinReq::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_joinReq_starmessage_2eproto.base);
  return *internal_default_instance();
}


void joinReq::Clear() {
// @@protoc_insertion_point(message_clear_start:txstar.joinReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(node_ != nullptr);
    node_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* joinReq::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .txstar.nodeinfo node = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_node(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* joinReq::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:txstar.joinReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .txstar.nodeinfo node = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::node(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:txstar.joinReq)
  return target;
}

size_t joinReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:txstar.joinReq)
  size_t total_size = 0;

  // required .txstar.nodeinfo node = 1;
  if (_internal_has_node()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *node_);
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void joinReq::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:txstar.joinReq)
  GOOGLE_DCHECK_NE(&from, this);
  const joinReq* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<joinReq>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:txstar.joinReq)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:txstar.joinReq)
    MergeFrom(*source);
  }
}

void joinReq::MergeFrom(const joinReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:txstar.joinReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_node()) {
    _internal_mutable_node()->::txstar::nodeinfo::MergeFrom(from._internal_node());
  }
}

void joinReq::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:txstar.joinReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void joinReq::CopyFrom(const joinReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:txstar.joinReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool joinReq::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (_internal_has_node()) {
    if (!node_->IsInitialized()) return false;
  }
  return true;
}

void joinReq::InternalSwap(joinReq* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(node_, other->node_);
}

::PROTOBUF_NAMESPACE_ID::Metadata joinReq::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void joinRsp::InitAsDefaultInstance() {
  ::txstar::_joinRsp_default_instance_._instance.get_mutable()->nxt_ = const_cast< ::txstar::nodeinfo*>(
      ::txstar::nodeinfo::internal_default_instance());
  ::txstar::_joinRsp_default_instance_._instance.get_mutable()->pre_ = const_cast< ::txstar::nodeinfo*>(
      ::txstar::nodeinfo::internal_default_instance());
}
class joinRsp::_Internal {
 public:
  using HasBits = decltype(std::declval<joinRsp>()._has_bits_);
  static const ::txstar::nodeinfo& nxt(const joinRsp* msg);
  static void set_has_nxt(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::txstar::nodeinfo& pre(const joinRsp* msg);
  static void set_has_pre(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

const ::txstar::nodeinfo&
joinRsp::_Internal::nxt(const joinRsp* msg) {
  return *msg->nxt_;
}
const ::txstar::nodeinfo&
joinRsp::_Internal::pre(const joinRsp* msg) {
  return *msg->pre_;
}
joinRsp::joinRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:txstar.joinRsp)
}
joinRsp::joinRsp(const joinRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_nxt()) {
    nxt_ = new ::txstar::nodeinfo(*from.nxt_);
  } else {
    nxt_ = nullptr;
  }
  if (from._internal_has_pre()) {
    pre_ = new ::txstar::nodeinfo(*from.pre_);
  } else {
    pre_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:txstar.joinRsp)
}

void joinRsp::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_joinRsp_starmessage_2eproto.base);
  ::memset(&nxt_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&pre_) -
      reinterpret_cast<char*>(&nxt_)) + sizeof(pre_));
}

joinRsp::~joinRsp() {
  // @@protoc_insertion_point(destructor:txstar.joinRsp)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void joinRsp::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete nxt_;
  if (this != internal_default_instance()) delete pre_;
}

void joinRsp::ArenaDtor(void* object) {
  joinRsp* _this = reinterpret_cast< joinRsp* >(object);
  (void)_this;
}
void joinRsp::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void joinRsp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const joinRsp& joinRsp::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_joinRsp_starmessage_2eproto.base);
  return *internal_default_instance();
}


void joinRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:txstar.joinRsp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(nxt_ != nullptr);
      nxt_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(pre_ != nullptr);
      pre_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* joinRsp::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .txstar.nodeinfo nxt = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_nxt(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required .txstar.nodeinfo pre = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_pre(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* joinRsp::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:txstar.joinRsp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .txstar.nodeinfo nxt = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::nxt(this), target, stream);
  }

  // required .txstar.nodeinfo pre = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::pre(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:txstar.joinRsp)
  return target;
}

size_t joinRsp::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:txstar.joinRsp)
  size_t total_size = 0;

  if (_internal_has_nxt()) {
    // required .txstar.nodeinfo nxt = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *nxt_);
  }

  if (_internal_has_pre()) {
    // required .txstar.nodeinfo pre = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *pre_);
  }

  return total_size;
}
size_t joinRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:txstar.joinRsp)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required .txstar.nodeinfo nxt = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *nxt_);

    // required .txstar.nodeinfo pre = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *pre_);

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void joinRsp::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:txstar.joinRsp)
  GOOGLE_DCHECK_NE(&from, this);
  const joinRsp* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<joinRsp>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:txstar.joinRsp)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:txstar.joinRsp)
    MergeFrom(*source);
  }
}

void joinRsp::MergeFrom(const joinRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:txstar.joinRsp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_nxt()->::txstar::nodeinfo::MergeFrom(from._internal_nxt());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_pre()->::txstar::nodeinfo::MergeFrom(from._internal_pre());
    }
  }
}

void joinRsp::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:txstar.joinRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void joinRsp::CopyFrom(const joinRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:txstar.joinRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool joinRsp::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (_internal_has_nxt()) {
    if (!nxt_->IsInitialized()) return false;
  }
  if (_internal_has_pre()) {
    if (!pre_->IsInitialized()) return false;
  }
  return true;
}

void joinRsp::InternalSwap(joinRsp* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(joinRsp, pre_)
      + sizeof(joinRsp::pre_)
      - PROTOBUF_FIELD_OFFSET(joinRsp, nxt_)>(
          reinterpret_cast<char*>(&nxt_),
          reinterpret_cast<char*>(&other->nxt_));
}

::PROTOBUF_NAMESPACE_ID::Metadata joinRsp::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void stabilizeReq::InitAsDefaultInstance() {
  ::txstar::_stabilizeReq_default_instance_._instance.get_mutable()->node_ = const_cast< ::txstar::nodeinfo*>(
      ::txstar::nodeinfo::internal_default_instance());
}
class stabilizeReq::_Internal {
 public:
  using HasBits = decltype(std::declval<stabilizeReq>()._has_bits_);
  static const ::txstar::nodeinfo& node(const stabilizeReq* msg);
  static void set_has_node(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::txstar::nodeinfo&
stabilizeReq::_Internal::node(const stabilizeReq* msg) {
  return *msg->node_;
}
stabilizeReq::stabilizeReq(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:txstar.stabilizeReq)
}
stabilizeReq::stabilizeReq(const stabilizeReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_node()) {
    node_ = new ::txstar::nodeinfo(*from.node_);
  } else {
    node_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:txstar.stabilizeReq)
}

void stabilizeReq::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_stabilizeReq_starmessage_2eproto.base);
  node_ = nullptr;
}

stabilizeReq::~stabilizeReq() {
  // @@protoc_insertion_point(destructor:txstar.stabilizeReq)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void stabilizeReq::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete node_;
}

void stabilizeReq::ArenaDtor(void* object) {
  stabilizeReq* _this = reinterpret_cast< stabilizeReq* >(object);
  (void)_this;
}
void stabilizeReq::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void stabilizeReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const stabilizeReq& stabilizeReq::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_stabilizeReq_starmessage_2eproto.base);
  return *internal_default_instance();
}


void stabilizeReq::Clear() {
// @@protoc_insertion_point(message_clear_start:txstar.stabilizeReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(node_ != nullptr);
    node_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* stabilizeReq::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .txstar.nodeinfo node = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_node(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* stabilizeReq::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:txstar.stabilizeReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .txstar.nodeinfo node = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::node(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:txstar.stabilizeReq)
  return target;
}

size_t stabilizeReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:txstar.stabilizeReq)
  size_t total_size = 0;

  // required .txstar.nodeinfo node = 1;
  if (_internal_has_node()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *node_);
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void stabilizeReq::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:txstar.stabilizeReq)
  GOOGLE_DCHECK_NE(&from, this);
  const stabilizeReq* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<stabilizeReq>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:txstar.stabilizeReq)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:txstar.stabilizeReq)
    MergeFrom(*source);
  }
}

void stabilizeReq::MergeFrom(const stabilizeReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:txstar.stabilizeReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_node()) {
    _internal_mutable_node()->::txstar::nodeinfo::MergeFrom(from._internal_node());
  }
}

void stabilizeReq::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:txstar.stabilizeReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void stabilizeReq::CopyFrom(const stabilizeReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:txstar.stabilizeReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool stabilizeReq::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (_internal_has_node()) {
    if (!node_->IsInitialized()) return false;
  }
  return true;
}

void stabilizeReq::InternalSwap(stabilizeReq* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(node_, other->node_);
}

::PROTOBUF_NAMESPACE_ID::Metadata stabilizeReq::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void stabilizeRsp::InitAsDefaultInstance() {
  ::txstar::_stabilizeRsp_default_instance_._instance.get_mutable()->pre_ = const_cast< ::txstar::nodeinfo*>(
      ::txstar::nodeinfo::internal_default_instance());
}
class stabilizeRsp::_Internal {
 public:
  using HasBits = decltype(std::declval<stabilizeRsp>()._has_bits_);
  static const ::txstar::nodeinfo& pre(const stabilizeRsp* msg);
  static void set_has_pre(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::txstar::nodeinfo&
stabilizeRsp::_Internal::pre(const stabilizeRsp* msg) {
  return *msg->pre_;
}
stabilizeRsp::stabilizeRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:txstar.stabilizeRsp)
}
stabilizeRsp::stabilizeRsp(const stabilizeRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_pre()) {
    pre_ = new ::txstar::nodeinfo(*from.pre_);
  } else {
    pre_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:txstar.stabilizeRsp)
}

void stabilizeRsp::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_stabilizeRsp_starmessage_2eproto.base);
  pre_ = nullptr;
}

stabilizeRsp::~stabilizeRsp() {
  // @@protoc_insertion_point(destructor:txstar.stabilizeRsp)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void stabilizeRsp::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete pre_;
}

void stabilizeRsp::ArenaDtor(void* object) {
  stabilizeRsp* _this = reinterpret_cast< stabilizeRsp* >(object);
  (void)_this;
}
void stabilizeRsp::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void stabilizeRsp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const stabilizeRsp& stabilizeRsp::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_stabilizeRsp_starmessage_2eproto.base);
  return *internal_default_instance();
}


void stabilizeRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:txstar.stabilizeRsp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(pre_ != nullptr);
    pre_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* stabilizeRsp::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .txstar.nodeinfo pre = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_pre(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* stabilizeRsp::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:txstar.stabilizeRsp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .txstar.nodeinfo pre = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::pre(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:txstar.stabilizeRsp)
  return target;
}

size_t stabilizeRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:txstar.stabilizeRsp)
  size_t total_size = 0;

  // required .txstar.nodeinfo pre = 1;
  if (_internal_has_pre()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *pre_);
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void stabilizeRsp::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:txstar.stabilizeRsp)
  GOOGLE_DCHECK_NE(&from, this);
  const stabilizeRsp* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<stabilizeRsp>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:txstar.stabilizeRsp)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:txstar.stabilizeRsp)
    MergeFrom(*source);
  }
}

void stabilizeRsp::MergeFrom(const stabilizeRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:txstar.stabilizeRsp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_pre()) {
    _internal_mutable_pre()->::txstar::nodeinfo::MergeFrom(from._internal_pre());
  }
}

void stabilizeRsp::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:txstar.stabilizeRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void stabilizeRsp::CopyFrom(const stabilizeRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:txstar.stabilizeRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool stabilizeRsp::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (_internal_has_pre()) {
    if (!pre_->IsInitialized()) return false;
  }
  return true;
}

void stabilizeRsp::InternalSwap(stabilizeRsp* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(pre_, other->pre_);
}

::PROTOBUF_NAMESPACE_ID::Metadata stabilizeRsp::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace txstar
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::txstar::nodeinfo* Arena::CreateMaybeMessage< ::txstar::nodeinfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::txstar::nodeinfo >(arena);
}
template<> PROTOBUF_NOINLINE ::txstar::successorReq* Arena::CreateMaybeMessage< ::txstar::successorReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::txstar::successorReq >(arena);
}
template<> PROTOBUF_NOINLINE ::txstar::successorRsp* Arena::CreateMaybeMessage< ::txstar::successorRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::txstar::successorRsp >(arena);
}
template<> PROTOBUF_NOINLINE ::txstar::successorNtf* Arena::CreateMaybeMessage< ::txstar::successorNtf >(Arena* arena) {
  return Arena::CreateMessageInternal< ::txstar::successorNtf >(arena);
}
template<> PROTOBUF_NOINLINE ::txstar::joinReq* Arena::CreateMaybeMessage< ::txstar::joinReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::txstar::joinReq >(arena);
}
template<> PROTOBUF_NOINLINE ::txstar::joinRsp* Arena::CreateMaybeMessage< ::txstar::joinRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::txstar::joinRsp >(arena);
}
template<> PROTOBUF_NOINLINE ::txstar::stabilizeReq* Arena::CreateMaybeMessage< ::txstar::stabilizeReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::txstar::stabilizeReq >(arena);
}
template<> PROTOBUF_NOINLINE ::txstar::stabilizeRsp* Arena::CreateMaybeMessage< ::txstar::stabilizeRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::txstar::stabilizeRsp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
